version: '3.8'


networks:
  services-net:
    name: services-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1


services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dle-docker-logs
    ports:
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - services-net
  argo:
    image: eu.gcr.io/dle-dev/argo:1.1.0
    networks:
      - services-net
    container_name: dle-argo
    restart: unless-stopped
    ports:
      - "8099:8099"
    depends_on:
      - proxy
      - dozzle

  ###################################################
  ## BEGIN REVERSE PROXY AND CERTS ##
  proxy:
    image: eu.gcr.io/dle-dev/proxy:1.5.0
    networks:
      - services-net
    container_name: dle-proxy
    restart: unless-stopped
    volumes:
      - ./volumes/proxy/certs:/etc/letsencrypt
      - /home/dle/services-logs/nginx:/var/log/nginx
      - ./volumes/proxy/acme:/etc/certbot
    ports:
      - "47808:47808"
      - "47809:47809"
    depends_on:
      - certbot
      - libre-backend
      - libre-frontend
      - libre-db
      - libre-redis
    env_file:
      - ./.${SERVICES_ENVIRONMENT}.ssl.env

  certbot:
    image: eu.gcr.io/dle-dev/certbot:latest
    networks:
      - services-net
    container_name: dle-certbot
    restart: unless-stopped
    volumes:
      - ./volumes/proxy/certs:/etc/letsencrypt
      - ./volumes/proxy/acme:/etc/certbot
    env_file:
      - ./.${SERVICES_ENVIRONMENT}.ssl.env
    ports:
      - "12079:12079"

  ###################################################
  ## BEGINE WEBSITE dle.dev ##
  site:
    image: eu.gcr.io/dle-dev/frontend:1.1.2
    networks:
      - services-net
    container_name: dle-site
    restart: unless-stopped
    expose:
      - 80
    depends_on:
      - argo

  santa:
    image: eu.gcr.io/dle-dev/sm-frontend:latest
    networks:
      - services-net
    container_name: dle-santa
    restart: unless-stopped
    depends_on:
      - argo
    expose:
      - 3000
  ###################################################
  ## BEGIN NEXTCLOUD ##
  cloud:
    image: eu.gcr.io/dle-dev/cloud:latest
    networks:
      services-net:
        ipv4_address: 172.19.0.99
    container_name: dle-cloud
    depends_on:
      - cloud-db
      - argo
    volumes:
      - ./volumes/cloud/html:/var/www/html
      - ./volumes/cloud/config:/var/www/html/config
      - ./volumes/cloud/custom-apps:/var/www/html/custom_apps
      - ./volumes/cloud/data:/var/www/html/data
      - ./volumes/cloud/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.cloud.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}

    restart: unless-stopped
    expose:
      - 80

  cloud-db:
    image: postgres:12.2
    networks:
      - services-net
    container_name: dle-cloud-db
    volumes:
      - ./volumes/cloud/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.cloud.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    restart: unless-stopped

  cloud-redis:
    image: redis:6.0.8
    networks:
      - services-net
    container_name: dle-cloud-redis
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    restart: unless-stopped
    expose:
      - 6379


  ###################################################
  ## BEGIN deluge ##
  deluge:
    image: linuxserver/deluge:latest
    depends_on:
      - argo
    networks:
      - services-net
    container_name: dle-deluge
    volumes:
      - ./volumes/deluge/config:/config
      - /mnt/md0/storage/Media/downloads:/downloads
      - /mnt/md0/storage/Media/Series:/Media
      - ./volumes/deluge/shared:/shared
    restart: unless-stopped
    env_file:
      - .linuxserver.env
    environment:
      - UMASK_SET=022
      - WEBUI_PORT=8112
    ports:
      - "6881:6881"
      - "6881:6881/udp"


  #################################################
  ### BEGIN RADARR ###
  radarr:
    image: linuxserver/radarr:latest
    networks:
      - services-net
    container_name: dle-radarr
    depends_on:
      - argo
    volumes:
      - ./volumes/radarr/config:/config
      - /mnt/md0/storage/Media/downloads:/downloads
      - /mnt/md0/storage/Media/Movies:/Media/Movies
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/radarr/shared:/shared
    expose:
      - 7878
    restart: unless-stopped
    env_file:
      - .linuxserver.env


  #################################################
  ### BEGIN SONARR ###
  sonarr:
    image: linuxserver/sonarr:latest
    networks:
      - services-net
    container_name: dle-sonarr
    depends_on:
      - argo
    volumes:
      - ./volumes/sonarr/config:/config
      - /mnt/md0/storage/Media/downloads:/downloads
      - /mnt/md0/storage/Media/Series:/Media/Series
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/sonarr/shared:/shared
    expose:
      - 8989
    restart: unless-stopped
    env_file:
      - .linuxserver.env

  #################################################
  ### BEGIN JACKETT ###
  jackett:
    image: linuxserver/jackett:latest
    networks:
      - services-net
    container_name: dle-jackett
    depends_on:
      - argo
    env_file:
      - .linuxserver.env
    volumes:
      - ./volumes/jackett/config:/config
      - /mnt/md0/storage/Media/downloads:/downloads
    expose:
      - 9117
    restart: unless-stopped

  #################################################
  ### BEGIN BITWARDEN ###
  bitwarden:
    image: bitwardenrs/server:latest
    networks:
      - services-net
    container_name: dle-bitwarden
    restart: unless-stopped
    depends_on:
      - argo
    env_file:
      - ./.${SERVICES_ENVIRONMENT}.bitwarden.env
    expose:
      - 80
      - 3012
    volumes:
      - /home/dle/services-logs/bitwarden/:/bitwarden-logs/
      - ./volumes/bitwarden/data:/data
      - ./volumes/bitwarden/attachments:/attachments

  bitwarden-private:
    image: bitwardenrs/server:latest
    networks:
      - services-net
    depends_on:
      - argo
    container_name: dle-bitwarden-private
    restart: unless-stopped
    env_file:
      - ./.${SERVICES_ENVIRONMENT}.bitwarden-private.env
    expose:
      - 80
      - 3012
    volumes:
      - /home/dle/services-logs/bitwarden-private/:/bitwarden-logs/
      - ./volumes/bitwarden-private/data:/data
      - ./volumes/bitwarden-private/attachments:/attachments

  #################################################
  ### BEGIN PAPERLESS ###
  paperless-broker:
    image: redis:6.0
    restart: unless-stopped
    networks:
      - services-net
    container_name: dle-paperless-broker
    command: --port 6380
    expose:
      - 6380

  paperless-db:
    image: postgres:13
    restart: unless-stopped
    container_name: dle-paperless-db
    networks:
      - services-net
    volumes:
      - /volumes/paperless-db:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: ${PAPERLESS_POSTGRES_DB}
      POSTGRES_USER: ${PAPERLESS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PAPERLESS_POSTGRES_PASSWORD}

  paperless-webserver:
    image: jonaswinkler/paperless-ng:latest
    restart: unless-stopped
    container_name: dle-paperless-webserver
    networks:
      - services-net
    depends_on:
      - paperless-db
      - paperless-broker
      - argo
    expose:
      - 8000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://paperless-webserver:8000" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./volumes/paperless/data:/usr/src/paperless/data
      - ./volumes/paperless/media:/usr/src/paperless/media
      - ./volumes/paperless/export:/usr/src/paperless/export
      - ./volumes/paperless/consume:/usr/src/paperless/consume
    env_file: .paperless-webserver.env
    environment:
      PAPERLESS_REDIS: redis://paperless-broker:6380
      PAPERLESS_DBHOST: paperless-db

  paperless-samba:
    image: elswork/samba
    container_name: dle-paperless-samba
    restart: unless-stopped
    environment:
      TZ: 'Europe/Zurich'
      SHARE: ${SAMBA_PERMISSIONS}
      USER: ${SAMBA_CREDENTIALS}
      HOSTNAME: "cassandra"
    command: '-u "1000:1000:paperless:paperless:c2oZv8yohL83ViQEJk7XbJC8eukwfige8CFlmyRXfAXNC91Ejz6YzolHcOfZx1WS" -s "shared:/data:rw:paperless"'
    networks:
      - services-net
    ports:
      - "139:139"
      - "445:445"
    volumes:
      - ./volumes/paperless/consume:/data


  #################################################
  ### LIBRE PHOTOS   ###
  libre-proxy:
    image: eu.gcr.io/dle-dev/libre-proxy:latest
    container_name: dle-libre-proxy
    restart: unless-stopped
    networks:
      - services-net
    depends_on:
      - libre-redis
      - libre-frontend
      - libre-db
      - libre-backend
    volumes:
      - ${LIBRE_PHOTOS_DIR}:/data
      - ${LIBRE_PRO_MEDIA_DIR}:/protected_media
    expose:
      - 80
  libre-db:
    image: postgres:13
    container_name: dle-libre-db
    environment:
      - POSTGRES_USER=${LIBRE_DB_USER}
      - POSTGRES_PASSWORD=${LIBRE_DB_PASS}
      - POSTGRES_DB=${LIBRE_DB_NAME}
    volumes:
      - ${LIBRE_DB_LOCATION}:/var/lib/postgresql/data
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off -c random_page_cost=1.0
    networks:
      - services-net
    restart: unless-stopped


  libre-frontend:
    image: reallibrephotos/librephotos-frontend:${LIBRE_TAG}
    container_name: dle-libre-frontend
    depends_on:
      - libre-backend
    networks:
      - services-net
    restart: unless-stopped

  libre-backend:
    image: reallibrephotos/librephotos:${LIBRE_TAG}
    container_name: dle-libre-backend
    volumes:
      - ${LIBRE_PHOTOS_DIR}:/data
      - ${LIBRE_PRO_MEDIA_DIR}:/protected_media
      - ${LIBRE_LOG_DIR}:/logs
      - ${LIBRE_CAHE_DIR}:/root/.cache

    environment:
      - SECRET_KEY=${LIBRE_SHHHH_KEY}
      - BACKEND_HOST=libre-backend
      - ADMIN_EMAIL=${LIBRE_ADMIN_EMAIL}
      - ADMIN_USERNAME=${LIBRE_USER_NAME}
      - ADMIN_PASSWORD=${LIBRE_USER_PASS}
      - DB_BACKEND=postgresql
      - DB_NAME=${LIBRE_DB_NAME}
      - DB_USER=${LIBRE_DB_USER}
      - DB_PASS=${LIBRE_DB_PASS}
      - DB_HOST=${LIBRE_DB_HOST}
      - DB_PORT=5432
      - REDIS_HOST=libre-redis
      - REDIS_PORT=6379
      - MAPBOX_API_KEY=${LIBRE_MAP_API_KEY}
      - WEB_CONCURRENCY=${LIBRE_GUNNI_WORKERS}
      - SKIP_PATTERNS=${LIBRE_SKIP_PATTERNS}
      - ALLOW_UPLOAD=${LIBRE_ALLOW_UPLOAD}
      - DEBUG=0
      - HEAVYWEIGHT_PROCESS=${LIBRE_HEAVYWEIGHT_PROCESS}
    networks:
      - services-net
    # Wait for Postgres
    restart: unless-stopped
    depends_on:
      - libre-db

  libre-redis:
    container_name: dle-libre-redis
    restart: unless-stopped
    image: redis:6
    networks:
      - services-net
