version: '3.8'


networks:
  services-net:
    name: services-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1


services:
  ###################################################
  ## BEGIN REVERSE PROXY AND CERTS ##
  nginx:
    image: eu.gcr.io/dle-dev/nginx:latest
    networks:
      - services-net
    container_name: dle-nginx
    restart: unless-stopped
    volumes:
      - ./volumes/proxy/certs:/etc/letsencrypt
      - /home/dle/services-logs/nginx:/var/log/nginx
      - ./volumes/proxy/acme:/etc/certbot
    ports:
      - 47800:47808
      - 47809:47809
    depends_on:
      - certbot
      - site
      - cloud
      - cloud-db
      - deluge
      - cloud-redis
      - jackett
      - radarr
      - sonarr
      - bitwarden
      - bitwarden-private
    env_file:
      - ./.${SERVICES_ENVIRONMENT}.ssl.env

  certbot:
    image: eu.gcr.io/dle-dev/certbot:latest
    networks:
      - services-net
    container_name: dle-certbot
    restart: unless-stopped
    volumes:
      - ./volumes/proxy/certs:/etc/letsencrypt
      - ./volumes/proxy/acme:/etc/certbot
    env_file:
      - ./.${SERVICES_ENVIRONMENT}.ssl.env
    ports:
      - 12079:12079


  ###################################################
  ## BEGINE WEBSITE dle.dev ##
  site:
    image: eu.gcr.io/dle-dev/frontend:0.1.23
    networks:
      - services-net
    container_name: dle-site
    restart: unless-stopped
    expose:
      - 80

  ## BEGINE WEBSITE staging.dle.dev ##
  site-staging:
    image: eu.gcr.io/dle-dev/frontend:staging
    networks:
      - services-net
    container_name: dle-site-staging
    restart: unless-stopped
    expose:
      - 80
  ###################################################
  ## BEGIN NEXTCLOUD ##
  cloud:
    image: eu.gcr.io/dle-dev/cloud:latest
    networks:
      - services-net
    container_name: dle-cloud
    depends_on:
      - cloud-db
    volumes:
      - ./volumes/cloud/html:/var/www/html
      - ./volumes/cloud/config:/var/www/html/config
      - ./volumes/cloud/custom-apps:/var/www/html/custom_apps
      - ./volumes/cloud/data:/var/www/html/data
      - ./volumes/cloud/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.cloud.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}

    restart: unless-stopped
    expose:
      - 80

  cloud-db:
    image: postgres:12.2
    networks:
      - services-net
    container_name: dle-cloud-db
    volumes:
      - ./volumes/cloud/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.cloud.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    restart: unless-stopped

  cloud-redis:
    image: redis:6.0.8
    networks:
      - services-net
    container_name: dle-cloud-redis
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    restart: unless-stopped
    expose:
      - 6379


  ###################################################
  ## BEGIN deluge ##
  deluge:
    image: linuxserver/deluge:latest
    networks:
      - services-net
    container_name: dle-deluge
    volumes:
      - ./volumes/deluge/config:/config
      - /mnt/md0/storage/Media/downloads:/downloads
      - /mnt/md0/storage/Media/Series:/Media
      - ./volumes/deluge/shared:/shared
    restart: unless-stopped
    env_file:
      - .linuxserver.env
    environment:
      - UMASK_SET=022
      - WEBUI_PORT=8112

      ###################################################
  ## BEGIN qBitTorrent ##
  qbt:
    image: linuxserver/qbittorrent:latest
    networks:
      - services-net
    container_name: dle-qbt
    volumes:
      - ./volumes/qbt/config:/config
      - /mnt/md0/storage/Media/downloads:/downloads
      - /mnt/md0/storage/Media/Series:/Media
      - ./volumes/qbt/shared:/shared
    expose:
      - 8082
      - 6881
      - 6881/udp
    restart: unless-stopped
    env_file:
      - .linuxserver.env
    environment:
      - UMASK_SET=022
      - WEBUI_PORT=8082


  #################################################
  ### BEGIN RADARR ###
  radarr:
    image: linuxserver/radarr:preview
    networks:
      - services-net
    container_name: dle-radarr
    volumes:
      - ./volumes/radarr/config:/config
      - /mnt/md0/storage/Media/downloads:/downloads
      - /mnt/md0/storage/Media/Movies:/Media/Movies
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/radarr/shared:/shared
    expose:
      - 7878
    restart: unless-stopped
    env_file:
      - .linuxserver.env


  #################################################
  ### BEGIN SONARR ###
  sonarr:
    image: linuxserver/sonarr:preview
    networks:
      - services-net
    container_name: dle-sonarr
    volumes:
      - ./volumes/sonarr/config:/config
      - /mnt/md0/storage/Media/downloads:/downloads
      - /mnt/md0/storage/Media/Series:/Media/Series
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/sonarr/shared:/shared
    expose:
      - 8989
    restart: unless-stopped
    env_file:
      - .linuxserver.env

  #################################################
  ### BEGIN JACKETT ###
  jackett:
    image: linuxserver/jackett:latest
    networks:
      - services-net
    container_name: dle-jackett
    env_file:
      - .linuxserver.env
    volumes:
      - ./volumes/jackett/config:/config
      - /mnt/md0/storage/Media/downloads:/downloads
    expose:
      - 9117
    restart: unless-stopped

  #################################################
  ### BEGIN BITWARDEN ###
  bitwarden:
    image: bitwardenrs/server:latest
    networks:
      - services-net
    container_name: dle-bitwarden
    restart: unless-stopped
    env_file:
      - ./.${SERVICES_ENVIRONMENT}.bitwarden.env
    expose:
      - 80
      - 3012
    volumes:
      - /home/dle/services-logs/bitwarden/:/bitwarden-logs/
      - ./volumes/bitwarden/data:/data
      - ./volumes/bitwarden/attachments:/attachments

  bitwarden-private:
    image: bitwardenrs/server:latest
    networks:
      - services-net
    container_name: dle-bitwarden-private
    restart: unless-stopped
    env_file:
      - ./.${SERVICES_ENVIRONMENT}.bitwarden-private.env
    expose:
      - 80
      - 3012
    volumes:
      - /home/dle/services-logs/bitwarden-private/:/bitwarden-logs/
      - ./volumes/bitwarden-private/data:/data
      - ./volumes/bitwarden-private/attachments:/attachments
