version: '3.7'


networks:
  services-net:
    name: services-net

services:
  ###################################################
  ## BEGIN REVERSE PROXY AND CERTS ##
  nginx:
    image: eu.gcr.io/dle-dev/nginx:1.1.1
    networks:
      - services-net
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./volumes/proxy/certs:/etc/letsencrypt
      - ./volumes/proxy/logs:/var/log/nginx
      - ./volumes/proxy/acme:/etc/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      #      - certbot
      - site
      - cloud
      - cloud-db
      - qbt
      - cloud-redis
      - jackett
      - radarr
      - sonarr
      - bitwarden
    env_file:
      - ./.${SERVICES_ENVIRONMENT}.ssl.env

  certbot:
    image: eu.gcr.io/dle-dev/certbot:1.0.1
    networks:
      - services-net
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./volumes/proxy/certs:/etc/letsencrypt
      - ./volumes/proxy/acme:/etc/certbot
    env_file:
      - ./.${SERVICES_ENVIRONMENT}.ssl.env
    ports:
      - 12079:12079


  ###################################################
  ## BEGINE WEBSITE dle.dev ##
  site:
    image: eu.gcr.io/dle-dev/frontend:0.1.21
    networks:
      - services-net
    container_name: site
    restart: unless-stopped
    expose:
      - 80

  ## BEGINE WEBSITE staging.dle.dev ##
  site-staging:
    image: eu.gcr.io/dle-dev/frontend:staging
    networks:
      - services-net
    container_name: site-staging
    restart: unless-stopped
    expose:
      - 80
  ###################################################
  ## BEGIN NEXTCLOUD ##
  cloud:
    image: nextcloud:apache
    networks:
      - services-net
    container_name: cloud
    depends_on:
      - cloud-db
    volumes:
      - ./volumes/cloud/html:/var/www/html
      - ./volumes/cloud/config:/var/www/html/config
      - ./volumes/cloud/custom-apps:/var/www/html/custom_apps
      - ./volumes/cloud/data:/var/www/html/data
      - ./volumes/cloud/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.cloud.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}

    restart: unless-stopped
    expose:
      - 80

  cloud-db:
    image: postgres:12.2
    networks:
      - services-net
    container_name: cloud-db
    volumes:
      - ./volumes/cloud/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.cloud.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    restart: unless-stopped

  cloud-redis:
    image: redis:6.0.8
    networks:
      - services-net
    container_name: cloud-redis
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    restart: unless-stopped
    expose:
      - 6379


  ###################################################
  ## BEGIN qBitTorrent ##
  qbt:
    image: linuxserver/qbittorrent:version-4.4.0202010251233-7101-0a2a71e83ubuntu18.04.1
    networks:
      - services-net
    container_name: qbt
    volumes:
      - ./volumes/qbt/config:/config
      - /home/dle/storage/Media/downloads:/downloads
      - /home/dle/storage/Media/:/Media
      - ./volumes/qbt/shared:/shared
    expose:
      - 8082
      - 6881
      - 6881/udp
    restart: unless-stopped
    env_file:
      - .linuxserver.env
    environment:
      - UMASK_SET=022
      - WEBUI_PORT=8082


  #################################################
  ### BEGIN RADARR ###
  radarr:
    image: linuxserver/radarr:preview
    networks:
      - services-net
    container_name: radarr
    volumes:
      - ./volumes/radarr/config:/config
      - /mnt/md0/storage/Media/downloads:/downloads
      - /mnt/md0/storage/Media/Movies:/Media/Movies
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/radarr/shared:/shared
    expose:
      - 7878
    restart: unless-stopped
    env_file:
      - .linuxserver.env


  #################################################
  ### BEGIN SONARR ###
  sonarr:
    image: linuxserver/sonarr:preview
    networks:
      - services-net
    container_name: sonarr
    volumes:
      - ./volumes/sonarr/config:/config
      - /mnt/md0/storage/Media/downloads:/downloads
      - /mnt/md0/storage/Media/Series:/Media/Series
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/sonarr/shared:/shared
    expose:
      - 8989
    restart: unless-stopped
    env_file:
      - .linuxserver.env

  #################################################
  ### BEGIN JACKETT ###
  jackett:
    image: linuxserver/jackett:latest
    networks:
      - services-net
    container_name: jackett
    env_file:
      - .linuxserver.env
    volumes:
      - ./volumes/jackett/config:/config
      - /mnt/md0/storage/Media/downloads:/downloads
    expose:
      - 9117
    restart: unless-stopped

  bitwarden:
    image: bitwardenrs/server:latest
    networks:
      - services-net
    container_name: bitwarden
    restart: unless-stopped
    env_file:
      - ./.${SERVICES_ENVIRONMENT}.bitwarden.env
    expose:
      - 80
      - 3012
    volumes:
     - ./volumes/bitwarden/data:/data
     - ./volumes/bitwarden/attachments:/attachments

