version: '3.8'


networks:
  services-net:
    name: services-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1


services:
  ###################################################
  ## BEGIN REVERSE PROXY AND CERTS ##
  nginx:
    image: eu.gcr.io/dle-dev/nginx:latest
    networks:
      - services-net
    container_name: dle-nginx
    restart: unless-stopped
    volumes:
      - ./volumes/proxy/certs:/etc/letsencrypt
      - /home/dle/services-logs:/var/log/nginx
      - ./volumes/proxy/acme:/etc/certbot
    ports:
      - 80:47808
      - 443:47809
    depends_on:
      - certbot
      - site
      - cloud
      - cloud-db
      - deluge
      - cloud-redis
      - jackett
      - radarr
      - sonarr
      - bitwarden
      - elastic
      - logstash
      - kibana
    env_file:
      - ./.${SERVICES_ENVIRONMENT}.ssl.env

  certbot:
    image: eu.gcr.io/dle-dev/certbot:latest
    networks:
      - services-net
    container_name: dle-certbot
    restart: unless-stopped
    volumes:
      - ./volumes/proxy/certs:/etc/letsencrypt
      - ./volumes/proxy/acme:/etc/certbot
    env_file:
      - ./.${SERVICES_ENVIRONMENT}.ssl.env
    ports:
      - 12079:12079


  ###################################################
  ## BEGINE WEBSITE dle.dev ##
  site:
    image: eu.gcr.io/dle-dev/frontend:0.1.23
    networks:
      - services-net
    container_name: dle-site
    restart: unless-stopped
    expose:
      - 80

  ## BEGINE WEBSITE staging.dle.dev ##
  site-staging:
    image: eu.gcr.io/dle-dev/frontend:staging
    networks:
      - services-net
    container_name: dle-site-staging
    restart: unless-stopped
    expose:
      - 80
  ###################################################
  ## BEGIN NEXTCLOUD ##
  cloud:
    image: eu.gcr.io/dle-dev/cloud:1.0.1
    networks:
      - services-net
    container_name: dle-cloud
    depends_on:
      - cloud-db
    volumes:
      - ./volumes/cloud/html:/var/www/html
      - ./volumes/cloud/config:/var/www/html/config
      - ./volumes/cloud/custom-apps:/var/www/html/custom_apps
      - ./volumes/cloud/data:/var/www/html/data
      - ./volumes/cloud/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.cloud.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}

    restart: unless-stopped
    expose:
      - 80

  cloud-db:
    image: postgres:12.2
    networks:
      - services-net
    container_name: dle-cloud-db
    volumes:
      - ./volumes/cloud/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./.cloud.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    restart: unless-stopped

  cloud-redis:
    image: redis:6.0.8
    networks:
      - services-net
    container_name: dle-cloud-redis
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    restart: unless-stopped
    expose:
      - 6379


  ###################################################
  ## BEGIN deluge ##
  deluge:
    image: linuxserver/deluge:latest
    networks:
      - services-net
    container_name: dle-deluge
    volumes:
      - ./volumes/deluge/config:/config
      - /mnt/md0/storage/Media/downloads:/downloads
      - /mnt/md0/storage/Media/Series:/Media
      - ./volumes/deluge/shared:/shared
    restart: unless-stopped
    env_file:
      - .linuxserver.env
    environment:
      - UMASK_SET=022
      - WEBUI_PORT=8112

      ###################################################
  ## BEGIN qBitTorrent ##
  qbt:
    image: linuxserver/qbittorrent:latest
    networks:
      - services-net
    container_name: dle-qbt
    volumes:
      - ./volumes/qbt/config:/config
      - /mnt/md0/storage/Media/downloads:/downloads
      - /mnt/md0/storage/Media/Series:/Media
      - ./volumes/qbt/shared:/shared
    expose:
      - 8082
      - 6881
      - 6881/udp
    restart: unless-stopped
    env_file:
      - .linuxserver.env
    environment:
      - UMASK_SET=022
      - WEBUI_PORT=8082


  #################################################
  ### BEGIN RADARR ###
  radarr:
    image: linuxserver/radarr:preview
    networks:
      - services-net
    container_name: dle-radarr
    volumes:
      - ./volumes/radarr/config:/config
      - /mnt/md0/storage/Media/downloads:/downloads
      - /mnt/md0/storage/Media/Movies:/Media/Movies
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/radarr/shared:/shared
    expose:
      - 7878
    restart: unless-stopped
    env_file:
      - .linuxserver.env


  #################################################
  ### BEGIN SONARR ###
  sonarr:
    image: linuxserver/sonarr:preview
    networks:
      - services-net
    container_name: dle-sonarr
    volumes:
      - ./volumes/sonarr/config:/config
      - /mnt/md0/storage/Media/downloads:/downloads
      - /mnt/md0/storage/Media/Series:/Media/Series
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/sonarr/shared:/shared
    expose:
      - 8989
    restart: unless-stopped
    env_file:
      - .linuxserver.env

  #################################################
  ### BEGIN JACKETT ###
  jackett:
    image: linuxserver/jackett:latest
    networks:
      - services-net
    container_name: dle-jackett
    env_file:
      - .linuxserver.env
    volumes:
      - ./volumes/jackett/config:/config
      - /mnt/md0/storage/Media/downloads:/downloads
    expose:
      - 9117
    restart: unless-stopped

  #################################################
  ### BEGIN BITWARDEN ###
  bitwarden:
    image: bitwardenrs/server:latest
    networks:
      - services-net
    container_name: dle-bitwarden
    restart: unless-stopped
    env_file:
      - ./.${SERVICES_ENVIRONMENT}.bitwarden.env
    expose:
      - 80
      - 3012
    volumes:
      - ./volumes/bitwarden/data:/data
      - ./volumes/bitwarden/attachments:/attachments

  #################################################
  ### BEGIN ELK ###
  elastic:
    image: eu.gcr.io/dle-dev/elastic:latest
    container_name: dle-elk-elastic
    restart: unless-stopped
    volumes:
      - ./volumes/elastic:/usr/share/elasticsearch/data/
    expose:
      - 9200
      - 9300
    environment:
      ES_JAVA_OPTS: "-Xmx5g -Xms5g"
    networks:
      - services-net
  logstash:
    image: eu.gcr.io/dle-dev/logstash:latest
    container_name: dle-elk-logstash
    restart: unless-stopped
    volumes:
      - /home/dle/services-logs:/home/proxy_logs:ro
    expose:
      - 1025/udp
      - 5000
      - 9600
    environment:
      LS_JAVA_OPTS: "-Xmx5g -Xms5g"
    networks:
      - services-net
    depends_on:
      - elastic
  kibana:
    image: eu.gcr.io/dle-dev/kibana:latest
    container_name: dle-elk-kibana
    restart: unless-stopped
    expose:
      - 5601
    networks:
      - services-net
    depends_on:
      - elastic
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.11.2
    user: root
    container_name: dle-elk-metricbeat
    restart: unless-stopped
    depends_on:
      - elastic
      - logstash
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - ./volumes/metricbeat/:/usr/share/metricbeat/data
    networks:
      - services-net
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.11.2
    container_name: dle-elk-filebeat
    # https://github.com/docker/swarmkit/issues/1951
    # Need to override user so we can access the log files, and docker.sock
    restart: unless-stopped
    user: root
    depends_on:
      - elastic
      - logstash
    networks:
      - services-net
    command: [ "--strict.perms=false" ]
    volumes:
      - ./volumes/filebeat:/usr/share/filebeat/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      # This is needed for filebeat to load container log path as specified in filebeat.yml
      - /mnt/md0/docker/containers/:/var/lib/docker/containers/:ro
#      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      # This is needed for filebeat to load logs for system and auth modules
      - /var/log/:/var/log/:ro
      # This is needed for filebeat to load logs for auditd module. you might have to install audit system
      # on ubuntu first (sudo apt-get install -y auditd audispd-plugins)
      - /var/log/audit/:/var/log/audit/:ro