

networks:
  services-net:
    name: services-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1


include:
  - ./compose/proxy.yml
  - ./compose/websites.yml
  - ./compose/cloud.yml
  - ./compose/media.yml
  - ./compose/paperless.yml
  - ./compose/brain.yml
  - ./compose/scrutiny.yml
  - ./compose/autobase.yml
  - ./compose/immich.yml