worker_processes auto;
events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log warn;

    sendfile on;
    keepalive_timeout 65;

    # Define a basic authentication setup
    auth_basic "Restricted Area";
    auth_basic_user_file /etc/nginx/.htpasswd;

    server {
        listen 57808;  # Listen on the default HTTP port

        location / {
            # Proxy requests to the service running on the same Docker network
            proxy_pass http://owntracks-recorder:8083;  # Replace with the appropriate service/container name and port
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}