

services:
  cloud:
    image: eu.gcr.io/dle-dev/cloud:30.0.4
    container_name: cloud
    networks:
      services-net:
        ipv4_address: 172.19.0.99
    depends_on:
      - cloud-db
      - argo
      - cloud-redis
    volumes:
      - ../volumes/cloud/html:/var/www/html
      - ../volumes/cloud/config:/var/www/html/config
      - ../volumes/cloud/custom-apps:/var/www/html/custom_apps
      - ../volumes/cloud/data:/var/www/html/data
      - ../volumes/cloud/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../.cloud.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
    restart: unless-stopped
    expose:
      - 80

  cloud-db:
    image: postgres:12.2
    container_name: cloud-db
    networks:
      - services-net
    volumes:
      - ../volumes/cloud/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../.cloud.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    restart: unless-stopped

  cloud-redis:
    image: redis:6.0.8
    networks:
      - services-net
    container_name: cloud-redis
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    restart: unless-stopped
    expose:
      - 6379 