

services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    restart: unless-stopped
    networks:
      - services-net
    ports:
      - "8002:8080" # webapp
      - "8003:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ../volumes/scrutiny/config:/opt/scrutiny/config
      - ../volumes/scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/nvme0"
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
      - "/dev/sdd"
      - "/dev/sde"
      - "/dev/sdf"
      - "/dev/sdg" 