input {
  file {
    type => "fail2ban"
    start_position => "beginning"
    path => [ "/home/fail2ban/fail2ban.log" ]
  }
}

filter {
  if [type] == "fail2ban" {
    grok {
      patterns_dir => "/etc/logstash/patterns"
      match => [
        "message", "%{F2B_DATE:date} %{F2B_ACTION} %{WORD:level} %{F2B_JAIL} %{WORD:action} %{IP:ip}",
        "message", "%{F2B_DATE:date} %{F2B_ACTION} %{F2B_LEVEL} %{GREEDYDATA:msg}?"
      ]
    }

    geoip {
      source => "ip"
    }
  }
}

output {
    elasticsearch {
        hosts => "elastic:9200"
        user => "elastic-user"
        password => "elastic-password"
        index => "fail2ban"
        ecs_compatibility => disabled
    }
}