input {
  file {
    type => "fail2ban"
    start_position => "beginning"
    path => [ "/home/fail2ban/fail2ban.log" ]
  }
}

filter {
    if [type] == "fail2ban" {
        grok {
            patterns_dir => ["/usr/share/logstash/patterns"]
            match => [ "message", "%{FAIL2BAN_BAN_ACTION}" ]
            add_tag => ["BAN"]
        }
        grok {
            patterns_dir => [ "/usr/share/logstash/patterns" ]
            match => [ "message", "%{FAIL2BAN_RESTORE_BAN}" ]
            add_tag => ["RESTORE_BAN"]
        }
        grok {
            patterns_dir => [ "/usr/share/logstash/patterns" ]
            match => [ "message", "%{FAIL2BAN_ALREADY_BANNED}" ]
            add_tag => ["ALREADY_BANNED "]


        }
        geoip {
            source => "clientip"
        }
        mutate {
            convert => [ "[geoip][coordinates]", "float" ]
        }
    }
}

output {
    elasticsearch {
        hosts => "elastic:9200"
        user => "elastic-user"
        password => "elastic-password"
        index => "fail2ban"
        ecs_compatibility => disabled
    }
}