input {
    udp {
        port => 1025
        queue_size => 50000
        type => "nginx"
    }
}

filter {
    grok {
        match => {
            "message" => "%{COMBINEDAPACHELOG}"
        }
    }
    date {
        match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
    }
}

output {
    elasticsearch {
        hosts => "elasticsearch:9200"
        index => "nginx"
    }
}